# Generated by Django 6.0.6 on 2026-06-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_product_unit_price_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
